### ISSUE TITLE
[REFACTOR] Tags 

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1271] opened 2019-09-01 23:39 UTC
## Expected behaviour

Tags component should be able to render a list of tags that don't contain links `<a>`

## Current behaviour

Tags only contain list of tags that have links `<a>`

## Steps to reproduce

1. https://pattern-lib-unimelb.netlify.com/?selectedKind=Tags&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

## Possible solution

```
<ul class="tags__list">
  <li class="tags__item list-reset">
    <a href="" class="tags__link">...</a>
  </li>
</ul>
```

and

```
<ul class="tags__list">
  <li class="tags__item list-reset">
    ...
  </li>
</ul>
```

**Comment by jaredh-um** [comment] 2021-03-01 03:31
@gepifanio Could you explain what the issue is with this one? That tags can only be input/output as `<a>`? The story seems to show both with and without...

**Comment by gepifanio** [comment] 2021-03-01 04:46
It has been done already. Closing this issue.

**Closed by gepifanio** 2021-03-01 04:46 UTC
Labels: bug, gen-2
